#!/bin/bash

banner() {

clear
printf "\e[0m\n"

printf "\e[0;36m █▀█░█▀█░█▀█░█▀█░█░█░█▄█░█▀█░█░█░█▀▀\e[0m\n"
printf "\e[0;36m █▀█░█░█░█░█░█░█░░█░░█░█░█░█░█░█░▀▀█\e[0m\n"
printf "\e[0;36m ▀░▀░▀░▀░▀▀▀░▀░▀░░▀░░▀░▀░▀▀▀░▀▀▀░▀▀▀\e[0m\n"                   
printf "\e[0m\n"
printf "\e[0m\e[1;33m    Coded By Pormes \e[0m\e[1;31m(\e[0m\e[1;33m Supportme Click Subscribe \e[0m\e[1;31m)\e[0m\n"

}

menu() {
printf "\e[0m\n"
printf "\e[0m\e[0;36m  [\e[0m\e[0;36m01\e[0m\e[0;36m]\e[0m\e[0;36m Connect to My IP\e[0m\n"
printf "\e[0m\e[0;36m  [\e[0m\e[0;36m02\e[0m\e[0;36m]\e[0m\e[0;36m Tracking Ip\e[0m\n"
printf "\e[0m\e[0;36m  [\e[0m\e[0;36m00\e[0m\e[0;36m]\e[0m\e[0;36m Exit\e[0m\n"
printf "\e[0m\n"
read -p $'  \e[0;36m[\e[0m\e[0;36m~\e[0m\e[0;36m]\e[0m\e[0;36m Select An Option \e[0m\e[0;36m: \e[0m\e[0;36m\en' option

if [[ $option == 1 || $option == 01 ]]; then
myipaddr
elif [[ $option == 2 || $option == 02 ]]; then
useripaddr
elif [[ $option == 0 || $option == 00 ]]; then
sleep 1
printf "\e[0m\n"
printf "\e[0m\n"
exit 1

else
printf " \e[0;36m[\e[0m\e[0;36m!\e[0m\e[0;36m]\e[0m\e[0;36m Invalid option \e[0;36m[\e[0m\e[0;36m!\e[0m\e[0;36m]\e[0m\n"
sleep 1
banner
menu
fi

}
myipaddr() {

myipaddripapico=$(curl -s "https://ipapi.co//json" -L)
myipaddripapicom=$(curl -s "http://ip-api.com/json/" -L)
myip=$(echo $myipaddripapico | grep -Po '(?<="ip":)[^,]*' | tr -d '[]"')
mycity=$(echo $myipaddripapico | grep -Po '(?<="city":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
myregion=$(echo $myipaddripapico | grep -Po '(?<="region":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mycountry=$(echo $myipaddripapico | grep -Po '(?<="country_name":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mylat=$(echo $myipaddripapicom | grep -Po '(?<="lat":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mylon=$(echo $myipaddripapicom | grep -Po '(?<="lon":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mytime=$(echo $myipaddripapicom | grep -Po '(?<="timezone":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mypostal=$(echo $myipaddripapicom | grep -Po '(?<="zip":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
myisp=$(echo $myipaddripapico | grep -Po '(?<="org":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
myasn=$(echo $myipaddripapico | grep -Po '(?<="asn":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mycountrycode=$(echo $myipaddripapico | grep -Po '(?<="country_code":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mycurrency=$(echo $myipaddripapico | grep -Po '(?<="currency":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mylanguage=$(echo $myipaddripapico | grep -Po '(?<="languages":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
mycalling=$(echo $myipaddripapico | grep -Po '(?<="country_calling_code":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')

banner
printf "\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  Ip Address    \e[0m\e[0;36m:\e[0m\e[0;36m   $myip\e[0m\n"
printf "  \e[0m\e[0;36m  City          \e[0m\e[0;36m:\e[0m\e[0;36m   $mycity\e[0m\n"
printf "  \e[0m\e[0;36m  Region        \e[0m\e[0;36m:\e[0m\e[0;36m   $myregion\e[0m\n"
printf "  \e[0m\e[0;36m  Country       \e[0m\e[0;36m:\e[0m\e[0;36m   $mycountry\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  Latitude      \e[0m\e[0;36m:\e[0m\e[0;92m    $mylat\e[0m\n"
printf "  \e[0m\e[0;36m  Longitude     \e[0m\e[0;36m:\e[0m\e[0;92m    $mylon\e[0m\n"
printf "  \e[0m\e[0;36m  Time Zone     \e[0m\e[0;36m:\e[0m\e[0;92m    $mytime\e[0m\n"
printf "  \e[0m\e[0;36m  Postal Code   \e[0m\e[0;36m:\e[0m\e[0;92m    $mypostal\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  ISP           \e[0m\e[0;36m:\e[0m\e[0;92m   $myisp\e[0m\n"
printf "  \e[0m\e[0;36m  ASN           \e[0m\e[0;36m:\e[0m\e[0;92m   $myasn\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  Country Code  \e[0m\e[0;36m:\e[0m\e[0;36m   $mycountrycode\e[0m\n"
printf "  \e[0m\e[0;36m  Currency      \e[0m\e[0;36m:\e[0m\e[0;36m   $mycurrency\e[0m\n"
printf "  \e[0m\e[0;36m  Languages     \e[0m\e[0;36m:\e[0m\e[0;36m   $mylanguage\e[0m\n"
printf "  \e[0m\e[0;36m  Calling Code  \e[0m\e[0;36m:\e[0m\e[0;36m   $mycalling\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  GOOGLE Maps   \e[0m\e[0;36m:\e[0m\e[0;36m  https://maps.google.com/?q=$mylat,$mylon\e[0m\n"
sleep 5
printf "\e[0m\n"
printf "  \e[0m\e[1;91m[\e[0m\e[1;97m01\e[0m\e[1;91m]\e[0m\e[1;93m Return To Main Menu\e[0m\n"
printf "  \e[0m\e[1;91m[\e[0m\e[1;97m02\e[0m\e[1;91m]\e[0m\e[1;93m Exit\e[0m\n"
printf "\e[0m\n"
read -p $'  \e[1;31m>>\e[0m\e[1;96m  \en' mainorexit1

if [[ $mainorexit1 == 1 || $mainorexit1 == 01 ]]; then
banner
menu
elif [[ $mainorexit1 == 2 || $mainorexit1 == 02 ]]; then
printf "\e[0m\n"
printf "\e[0m\n"
exit 1

else
printf " \e[0;36m[\e[0m\e[0;36m!\e[0m\e[0;36m]\e[0m\e[0;36m Invalid option \e[0;36m[\e[0m\e[0;36m!\e[0m\e[0;36m]\e[0m\n"
sleep 1
banner
menu
fi

}

useripaddr() {

banner
printf "\e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
read -p $'  \e[0;36m[\e[0m\e[0;36m~\e[0m\e[0;36m]\e[0m\e[0;36m Input IP Address \e[0m\e[0;36m: \e[0m\e[0;37m\en' useripaddress

ipaddripapico=$(curl -s "https://ipapi.co/$useripaddress/json" -L)
ipaddripapicom=$(curl -s "http://ip-api.com/json/$useripaddress" -L)
userip=$(echo $ipaddripapico | grep -Po '(?<="ip":)[^,]*' | tr -d '[]"')
usercity=$(echo $ipaddripapico | grep -Po '(?<="city":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
useregion=$(echo $ipaddripapico | grep -Po '(?<="region":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
usercountry=$(echo $ipaddripapico | grep -Po '(?<="country_name":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
userlat=$(echo $ipaddripapicom | grep -Po '(?<="lat":)[^},]*' | tr -d '[]"' | se6 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
userlon=$(echo $ipaddripapicom | grep -Po '(?<="lon":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
usertime=$(echo $ipaddripapicom | grep -Po '(?<="timezone":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
userpostal=$(echo $ipaddripapicom | grep -Po '(?<="zip":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
userisp=$(echo $ipaddripapico | grep -Po '(?<="org":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
userasn=$(echo $ipaddripapico | grep -Po '(?<="asn":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
usercountrycode=$(echo $ipaddripapico | grep -Po '(?<="country_code":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
usercurrency=$(echo $ipaddripapico | grep -Po '(?<="currency":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
userlanguage=$(echo $ipaddripapico | grep -Po '(?<="languages":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')
usercalling=$(echo $ipaddripapico | grep -Po '(?<="country_calling_code":)[^},]*' | tr -d '[]"' | sed 's/\(<[^>]*>\|<\/>\|{1|}\)//g')

banner
printf "\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  Ip Address    \e[0m\e[0;36m:\e[0m\e[0;36m   $userip\e[0m\n"
printf "  \e[0m\e[0;36m  City          \e[0m\e[0;36m:\e[0m\e[0;36m   $usercity\e[0m\n"
printf "  \e[0m\e[0;36m  Region        \e[0m\e[0;36m:\e[0m\e[0;36m   $useregion\e[0m\n"
printf "  \e[0m\e[0;36m  Country       \e[0m\e[0;36m:\e[0m\e[0;36m   $usercountry\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  Latitude      \e[0m\e[0;36m:\e[0m\e[0;36m    $userlat\e[0m\n"
printf "  \e[0m\e[0;36m  Longitude     \e[0m\e[0;36m:\e[0m\e[0;36m    $userlon\e[0m\n"
printf "  \e[0m\e[0;36m  Time Zone     \e[0m\e[0;36m:\e[0m\e[0;36m    $usertime\e[0m\n"
printf "  \e[0m\e[0;36m  Postal Code   \e[0m\e[0;36m:\e[0m\e[0;36m    $userpostal\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  ISP           \e[0m\e[0;36m:\e[0m\e[0;36m   $userisp\e[0m\n"
printf "  \e[0m\e[0;36m  ASN           \e[0m\e[0;36m:\e[0m\e[0;36m   $userasn\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  Country Code  \e[0m\e[0;36m:\e[0m\e[0;36m   $usercountrycode\e[0m\n"
printf "  \e[0m\e[0;36m  Currency      \e[0m\e[0;36m:\e[0m\e[0;36m   $usercurrency\e[0m\n"
printf "  \e[0m\e[0;36m  Languages     \e[0m\e[0;36m:\e[0m\e[0;36m   $userlanguage\e[0m\n"
printf "  \e[0m\e[0;36m  Calling Code  \e[0m\e[0;36m:\e[0m\e[0;36m   $usercalling\e[0m\n"
printf "\e[0m\n"
printf "  \e[0m\e[0;36m  GOOGLE Maps   \e[0m\e[0;36m:\e[0m\e[0;36m  https://maps.google.com/?q=$userlat,$userlon\e[0m\n"
sleep 5
printf "\e[0m\n"
printf "  \e[0m\e[0;36m[\e[0m\e[0;36m01\e[0m\e[0;36m]\e[0m\e[0;36m Return To Main Menu\e[0m\n"
printf "  \e[0m\e[0;36m[\e[0m\e[0;36m02\e[0m\e[0;36m]\e[0m\e[0;36m Exit\e[0m\n"
printf "\e[0m\n"
read -p $'  \e[0;36m>>\e[0m\e[0;36m  \en' mainorexit2

if [[ $mainorexit2 == 1 || $mainorexit2 == 01 ]]; then
banner
menu
elif [[ $mainorexit2 == 2 || $mainorexit2 == 02 ]]; then
printf "\e[0m\n"
printf "\e[0m\n"
exit 1

else
printf " \e[0;36m[\e[0m\e[0;36m!\e[0m\e[0;36m]\e[0m\e[0;36m Invalid option \e[0;36m[\e[0m\e[0;36m!\e[0m\e[0;36m]\e[0m\n"
sleep 1
banner
menu
fi

}

banner
menu
